### ISSUE TITLE
possible to device to device connect?

### ISSUE THREAD

**Issue by Shadowstep33** [becvert/cordova-plugin-websocket-server#1]
is an active internet connection required? Could this work over bluetooth? NFC? Other radio frequencies?

**Comment by becvert** [comment]
An active internet connection should not be required.
It is working with WiFi devices on a LAN, not P2P via bluetooth or otherwise.

**Comment by Shadowstep33** [comment]
Ok thank you

**Comment by ghost** [comment]
hmm, bluetooth would be sweet :-)

**Comment by becvert** [comment]
I don't think a websocket server over bluetooth is relevant.
With BT your devices are paired and talk straight to each other.
No need for a WebSocket protocol.

**Comment by Shadowstep33** [comment]
You are likely right about the @becvert but the bluetooth communication does involve correctly identifying and pairing with your partner right? It would be useful if you could assign a websocket server an app specific ID and then that app just looks for other WS servers running on that app name/address. 

so all phones would try to connect to ws://com.my.app so now they don't have to pair and can always predictably connect to nearby servers. 

I also understand very little about bluetooth protocol so this is straight guessin :)
