### ISSUE TITLE
Unexpected response code: 403

### ISSUE THREAD

**Issue by myl142857** [becvert/cordova-plugin-websocket-server#10]
var socket = new WebSocket("ws://localhost:8888")
it will always generate console error message: WebSocket connection to "ws://localhost:8888" failed: Unexpected response code: 403

it is under IOS, and just use README's wsserver.start(8888, ....)

**Comment by becvert** [comment]
What are the values of the `origins` and `protocols` options?
Plus iOS returns `null` as the origin HTTP field I think.
Adding `null` to the `origins` option may fix your problem.

**Comment by myl142857** [comment]
wsserver.start(port, {
    // WebSocket Server
    'onStart' : function(addr, port) {
        console.log('Listening on %s:%d', addr, port);
    },
    'onStop' : function(addr, port) {
        console.log('Stopped listening on %s:%d', addr, port);
    },
    // WebSocket Connection
    'onOpen' : function(conn) {
        /\* conn: {
         'uuid' : '8e176b14-a1af-70a7-3e3d-8b341977a16e',
         'remoteAddr' : '192.168.1.10',
         'acceptedProtocol' : 'my-protocol-v1',
         'httpFields' : {...},
         'resource' : '/?param1=value1&param2=value2'
         } */
        console.log('A user connected from %s', conn.remoteAddr);
    },
    'onMessage' : function(conn, msg) {
        console.log(conn, msg);
    },
    'onClose' : function(conn, code, reason) {
        console.log('A user disconnected from %s', conn.remoteAddr);
    },
    'origins' : [ null ], // optional. validates the 'Origin' HTTP Header.
    'protocols' : [ 'my-protocol-v1', 'my-protocol-v2' ] // optional. validates the 'Sec-WebSocket-Protocol' HTTP Header.
});

**Comment by myl142857** [comment]
wsserver.start(port, {
    // WebSocket Server
    'onStart' : function(addr, port) {
        console.log('Listening on %s:%d', addr, port);
    },
    'onStop' : function(addr, port) {
        console.log('Stopped listening on %s:%d', addr, port);
    },
    // WebSocket Connection
    'onOpen' : function(conn) {
        /\* conn: {
         'uuid' : '8e176b14-a1af-70a7-3e3d-8b341977a16e',
         'remoteAddr' : '192.168.1.10',
         'acceptedProtocol' : 'my-protocol-v1',
         'httpFields' : {...},
         'resource' : '/?param1=value1&param2=value2'
         } */
        console.log('A user connected from %s', conn.remoteAddr);
    },
    'onMessage' : function(conn, msg) {
        console.log(conn, msg);
    },
    'onClose' : function(conn, code, reason) {
        console.log('A user disconnected from %s', conn.remoteAddr);
    },
    'origins' : null, // optional. validates the 'Origin' HTTP Header.
    'protocols' : [ 'my-protocol-v1', 'my-protocol-v2' ] // optional. validates the 'Sec-WebSocket-Protocol' HTTP Header.
});

**Comment by myl142857** [comment]
both do not work, same result of:  console error message: WebSocket connection to "ws://localhost:8888" failed: Unexpected response code: 403

**Comment by becvert** [comment]
remove `origins` and `protocols` altogether to start with.

then `origins` is optional
`origins` removed means anyone (any origin) can connect
`origins: [ 'file://' ]` means only devices (other cordova webviews?) can connect to the WS server.
`origins: [ 'file://', 'null' ]` to allow iOS devices as well ('null' as a string)
`origins: [ 'file://', 'null', 'http://localhost' ]` to allow local web browsers to connect also.
`origins: [ 'file://', 'null', 'http://mydomain' ]` to allow connections from mydomain in addition.

use `protocols` only if you actually implemented subprotocols (application-level protocols layered over the WebSocket Protocol)

**Comment by myl142857** [comment]
works well now, Great, Thanks!
