### ISSUE TITLE
Working sample ?

### ISSUE THREAD

**Issue by kohaistyle** [becvert/cordova-plugin-websocket-server#12]
I can't seem to have the plugin working. Compiles good in a cordova sample, but server never starts.
Maybe you it is not instanciated good, as the exported module is WebSocketServer, but you call cordova.plugins.wsserver in your sample code.

Do you have a working cordova project, by any chance ?
Thx a bunch

**Comment by becvert** [comment]
Nope, I don't have a sample project for you other than what is in the README.
cordova.plugins.wsserver is right.
Is it not starting in both Android and iOS?
Have you got some logging ouput in a console?

**Comment by kohaistyle** [comment]
Sorry for the late answer.
Ok i'll try to sort this out, nevermind ;)

Thanx for taking the time to answer !

**Comment by kohaistyle** [comment]
Hello there, 

Just to state that i sorted it out ... as always, just a misplaced bracket in the code. It's all working great now.

Thanx a lot for your lib and sorry for the dumb question ;)

**Comment by Germainbob** [comment]
I sorry kohaistyle, "unresolved variable wsserver" can you show a simple code on how you solved this. I am running onto the same issue.

thanks

**Comment by henokmengistu** [comment]
hi, i was trying to use cordova-plugin-websocket-server and i am having difficulties with:
          var wsserver = cordova.plugins.wsserver;
can u help me out, i used the the README, is there any other thing i need to import or install besides the plugin?
