### ISSUE TITLE
[iOS] Failed compiling

### ISSUE THREAD

**Issue by stephio** [becvert/cordova-plugin-websocket-server#14]
Hi,

it seams this is the only plugin around and I'm having a bad need for it, but compiling on iOS 10 gives the following error:

System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord(IAsyncResult asyncResult)
   at Mono.Security.Protocol.Tls.SslClientStream.SafeReceiveRecord(Stream s)
   at Mono.Security.Protocol.Tls.SslClientStream.OnNegotiateHandshakeCallback(IAsyncResult asyncResult)
   at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback(IAsyncResult asyncResult)

Could you please share your thoughts about this issue. Do I need something else installed?

Thank you!

**Comment by becvert** [comment]
Hi @stephio

There's nothing in the stacktrace that belongs to this plugin. So it's hard to say.
I do believe you're using http://www.mono-project.com/ or https://www.xamarin.com/, right?
I would dig on that side.

Also FYI, this plugin does not support SSL (as I see SSL stuff in the stacktrace)  

Good luck and please let us know when you fix the problem.

**Comment by stephio** [comment]
Dear Becvert,

thank you for your information.
I'm using Telerik AppBuilder with a blank Cordova 4 project. I just add your plugin and compiled.
The errors are pretty strange, I don't know Swift and the syntax could be fine,  but the Telerik server is complaining about the ? mark, it could happen that there is no support for Swift?
This is one of the errors:

Error: [xcode-build] Compile /tmp/builds/Zo0JQG8fqCGuxgoiir/app/Plugins/cordova-plugin-websocket-server-master/src/ios/WebSocketServer.swift: /tmp/builds/Zo0JQG8fqCGuxgoiir/app/Plugins/cordova-plugin-websocket-server-master/src/ios/WebSocketServer.swift:12:5: error: expected declaration
    fileprivate var wsserver: PSWebSocketServer?
    ^
/tmp/builds/Zo0JQG8fqCGuxgoiir/app/Plugins/cordova-plugin-websocket-server-master/src/ios/WebSocketServer.swift:12:16: error: consecutive declarations on a line must be separated by ';'
    fileprivate var wsserver: PSWebSocketServer?
               ^
               ;
/tmp/builds/Zo0JQG8fqCGuxgoiir/app/Plugins/cordova-plugin-websocket-server-master/src/ios/WebSocketServer.swift:13:5: error: expected declaration
    fileprivate var port: Int?
    ^
/tmp/builds/Zo0JQG8fqCGuxgoiir/app/Plugins/cordova-plugin-websocket-server-master/src/ios/WebSocketServer.swift:13:16: error: consecutive declarations on a line must be separated by ';'
    fileprivate var port: Int?
               ^
               ;

Thank you!

**Comment by becvert** [comment]
Swift version is 3.0.
Does telerik support it?
You could try a previous release of this plugin

**Comment by becvert** [comment]
Can we close this issue?
