### ISSUE TITLE
[Android] Server starts listening but doesn't respond to connections

### ISSUE THREAD

**Issue by mikeCm14** [becvert/cordova-plugin-websocket-server#16]
Hi,

Copy-pasted it from your  readme example. The server even connects (according to the client) but it looks like it doesn't enter to the onOpen() function to get the connection data.

I'm using Ionic.

Thanks,

**Comment by becvert** [comment]
check origins and protocols options.

**Comment by mikeCm14** [comment]
They're both commented out.

**Comment by becvert** [comment]
What do the clients say exactly?
