### ISSUE TITLE
Listening on specific IP

### ISSUE THREAD

**Issue by hktari** [becvert/cordova-plugin-websocket-server#17]
I would like to specify an IP for the server to listen to. Is this possible ?

**Comment by becvert** [comment]
With the current implementation it is not possible.
Just out of curiosity, why do you want to do that?

**Comment by hktari** [comment]
The plan is to operate a device remotely. I have to listen to a specific ip:port in my mobile device application and the device automatically connects to the specified ip.

**Comment by hktari** [comment]
How much effort would it take to enable this feature in the current implementation of the plugin ? And what is the procedure/technique of doing so called ? I'd like to read more about it...

Thanks for your help :)

**Comment by becvert** [comment]
Your remote device should connect to your mobile handset on which runs the websocket server, is that it?

If you know Java and Swift, and by just looking at the code of this plugin, I guess you can come up with something fairly easily...

**Comment by hktari** [comment]
yes that's correct, oh well... Thank you for your help

**Comment by OrdinarySF** [comment]
I made a [capacitor(ionic) plugin](https://github.com/OrdinarySF/capacitor-websocket-client) that can support websocket remote connection, welcome to try it.
