### ISSUE TITLE
[iOS] crashes immediately upon connection

### ISSUE THREAD

**Issue by elewin** [becvert/cordova-plugin-websocket-server#18]
I'm using the code you have in your readme almost verbatim, but with orgins set to null and protocols set to null. As soon as I make a connection with a client using this code:
`		var ws = new WebSocket('ws://'+addr);
		ws.onopen = function (event) { 
           console.log('connected');
}`

My client will log the 'connected' line but the server device will crash to the "desktop"/app launcher of the device. Am I missing anything? It does this on two separate devices, one running iOS 9 and another on iOS 10

**Comment by bugnano** [comment]
I have the same issue here, on the server side XCode breaks on WebSocketServer.swift on line 282 when attempting a connection, but I have no idea on how to fix this issue

**Comment by becvert** [comment]
Thanks for reporting this issue.
I'll have a look. Tomorrow most probably.

**Comment by becvert** [comment]
Found it: a NPE while retrieving the URL query string.
Thanks @bugnano
I'll publish an update right away.

**Comment by becvert** [comment]
Done. Please let me know if it fixes your problem.

**Comment by bugnano** [comment]
Thank you, now everything works
