### ISSUE TITLE
[iOS] latency issue

### ISSUE THREAD

**Issue by becvert** [becvert/cordova-plugin-websocket-server#21]
[#20](https://github.com/becvert/cordova-plugin-websocket-server/issues/20#issuecomment-267351198)

**Comment by becvert** [comment]
@bugnano  Could #3 help you a little bit?

**Comment by bugnano** [comment]
I suspect that the latency issue has to do with Nagle's algorithm

https://en.wikipedia.org/wiki/Nagle's_algorithm

so, apparently setting the TCP_NODELAY option to the socket would fix the issue.

The question is: Does the websocket server library that you're using expose the socket options (or something similar to disable Nagle's algorithm), or should a bug request be filled also for the ios websocket server library project?

**Comment by becvert** [comment]
Good point.
Alas the socket options are not exposed.
Please ask [zwopple/PocketSocket](https://github.com/zwopple/PocketSocket/issues) for help.
Alternatively, if you are able to work this out, we could fork PocketSocket for the time being

**Comment by becvert** [comment]
Aren't you experiencing latency with an Android server too?
Because looking into the android server's code, it seems that TCP_NODELAY isn't enabled either.

I've been reading some more about this, and while an option can be provided server-side to turn it on/off, I think there's still an issue client side where Javascript WebSocket TCP_NODELAY isn't configurable (OS dependent). Please correct me if I'm wrong.

[the-caveats-of-tcp-nodelay](https://eklitzke.org/the-caveats-of-tcp-nodelay)
[sending-filler-data-on-websocket](http://stackoverflow.com/questions/19560163/sending-filler-data-on-websocket)

**Comment by bugnano** [comment]
That's strange, I thought that on Android the TCP_NODELAY option was enabled, as the latency on Android to Android connections is good.

To have a clear picture, this is the situation I'm facing:

Android server to Android client --> Good performance

iOS server to Android client --> Poor performance

Android server to iOS client --> Poor performance

iOS server to iOS client --> Poor performance

So, my proposed solution is to fix one problem at a time, and for me the next logical step would be to fix the iOS server to Android client issue, and probably the TCP_NODELAY option would fix this issue, we only have to try ;)

Still, you're right that we might not be able to do anything to fix the iOS client issue, but I think that that's another problem that we may address after fixing the iOS server.

**Comment by becvert** [comment]
> fix one problem at a time

I completely agree 👍

**Comment by becvert** [comment]
Please test branch 1.4.1 and tell me if you see any difference.

`wsserver.start(port, { ... tcpNoDelay : true ... })`

applies to Android and iOS servers

**Comment by becvert** [comment]
I just fixed missing file in branch 1.4.1.

**Comment by bugnano** [comment]
Ok, branch 1.4.1 fixes the iOS Server to Android Client issue, and it also seems to be slightly better on Android Server to Android client too.

Unfortunately, when it comes to iOS clients, the performance remains very poor, but at this point I think that it's a problem with iOS WkWebView/Safari than with the wsserver plugin, so, as far as I'm concerned, I think that we can close this issue.

**Comment by becvert** [comment]
Thank you. Closing now.
