### ISSUE TITLE
[iOS] Fails to build in Xcode: WebSocketServer-Bridging-Header.h' file not found

### ISSUE THREAD

**Issue by elewin** [becvert/cordova-plugin-websocket-server#22]
After installing this plugin, my build in Xcode fails with the error "'WebSocketServer-Bridging-Header.h' file not found"

Is anyone else encountering this?

**Comment by elewin** [comment]
It looks like there's a "Bridging-Header.h" file in the directory its looking in, but not the websocket one. I do see it in the repo of course though.

Manually copying the files from the repo download into the directory it was expecting them in worked (including the PSWebSocket files). Is this just a problem with the cordova plugin add process? Or am I just a strange outlier?

**Comment by becvert** [comment]
When you create a cordova project it adds a `Bridging-Header.h` file to the iOS platform.
Then when you add this plugin, it should add `#import "WebSocketServer-Bridging-Header.h"` into it.
No manual copying should be required.
I don't know what went wrong. I would remove/re-add the plugin.

**Comment by elewin** [comment]
I'm adding it to an existing cordova (Ionic, specifically) project, and tried removing and re-adding it. I had an older version of this plugin that had since been removed previously, I'm not sure if that complicated things. I'll play around with it some more and report back if I can figure anything out. Thanks.

**Comment by elewin** [comment]
After running `ionic state reset` (which wipes out all cordova plugins and platforms and re-installs them on Ionic), everything installed correctly and it seems to be running fine now. If anyone else encounters this, try that fix.
