### ISSUE TITLE
TCP_NODELAY

### ISSUE THREAD

**Issue by ramezrafla** [becvert/cordova-plugin-websocket-server#30]
Thanks @becvert  for this amazing plugin. A life-saver and works so well!

In the README, you mention that `tcpNoDelay` enables / disables Nagle's algorithm. If I am not mistaken, `tcpNoDelay = false` **enables** Nagle's algorithm. Am I correct?

**Comment by becvert** [comment]
that's right 👍

**Comment by ramezrafla** [comment]
Want me to PR readme?

**Comment by becvert** [comment]
what would you write instead?

**Comment by ramezrafla** [comment]
I would explain that tcpnodelay = true disables Nagle's algorithm (which attempts to batch packets to reduce bandwidth / overhead), and that tcpnodelay = true is most useful for of real-time communication

**Comment by becvert** [comment]
> // disables Nagle's algorithm.

without "enable" it's good enough to me.

**Comment by becvert** [comment]
thanks @ramezrafla

**Comment by ramezrafla** [comment]
Hehe .. much simpler, I agree. Thanks @becvert for taking my feedback into account.
