### ISSUE TITLE
window.plugins is undefined

### ISSUE THREAD

**Issue by homakov** [becvert/cordova-plugin-websocket-server#32]
Using this on macos:

```
cordova create testwebsocket

cd testwebsocket

cordova platform add android

cordova plugin add cordova-plugin-websocket-server

cordova run android
```

window.plugins and wsserver are undefined. Is this plugin still supported?

By the way how can I contact you? Interest in a contract gig for similar functionality?

**Comment by homakov** [comment]
Figured out it's under window.cordova.plugins. Weird, i used window.plugins before... Anyway still interested in reaching out to discuss a project

**Comment by homakov** [comment]
Btw @becvert do you know any way how to connect to that websocket from safari? It denies all localhost requests. Works on Android.

**Comment by becvert** [comment]
Do you use the 'origins' option?

**Comment by becvert** [comment]
support@becvertprod.fr to reach me in private
