### ISSUE TITLE
How to send message from client?

### ISSUE THREAD

**Issue by shkhalid** [becvert/cordova-plugin-websocket-server#35]
The server is working on android. But how can I send  simple text  message from client.

**Comment by becvert** [comment]
Just use any WebSocket client. 
URL for connecting to the server would look like `ws://<ip or hostname>:<port>`

**Comment by elewin** [comment]
Establish a websocket connection from the client to the server. Then create an event listener on the server  to listen for events sent from connected clients, and use the send method on the client to send events from the client to the server.
See https://developer.mozilla.org/en-US/docs/Web/API/WebSocket  for more info

**Comment by shkhalid** [comment]
I have tried on that but i did not get any useful result. 
```
socket.on('connect_error', function(error) {
     console.log("Connection error: " + error);
});
```
I am getting this output => "Connection error: timeout"
Can you please send some simple example?

**Comment by elewin** [comment]
I have't tested this code, but it should hopefuly give you a starting point.

on the client:
```
var addr = //server address here
var ws = new WebSocket('ws://'+addr); 

ws.onopen = function (event) { 
console.log('connected'); 
}
```
once you are connected to the server, you can try
```
ws.send('i am sending a message!')
```
on the server:
```
socket.onMessage = function(event){
console.log('i got this message:', event)
}

```

Further reading: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

**Comment by becvert** [comment]
thank you @elewin
closing now.
