### ISSUE TITLE
ionic3 use it

### ISSUE THREAD

**Issue by u2young** [becvert/cordova-plugin-websocket-server#38]
How can i create class to use ?  
Write a declarative typescript class   ?

**Comment by becvert** [comment]
No idea. Please address your issue to the ionic or typescript communities. Thank you. Closing now.

**Comment by OliverTr54** [comment]
Hey @Paul101432...
... I was able to make it work with Ionic 3. Just have a look: [https://github.com/becvert/cordova-plugin-websocket-server/issues/43](https://github.com/becvert/cordova-plugin-websocket-server/issues/43) 

Here you could find some sample code that works. But keep in mind - inside the callback functions 'onOpen', etc. - you could not access class variables - you gotta find some other way.

Oliver
