### ISSUE TITLE
websocket server in ionic 2

### ISSUE THREAD

**Issue by dburgosm** [becvert/cordova-plugin-websocket-server#4]
Hello Becvert, 

I'm looking for a plugin or example to run a websocket server in ionic 2, Is possible with this plugin? Do you have some example from this case? 

Best regards
David

**Comment by becvert** [comment]
Hi David,
I'm not familiar with Ionic. My guess is that you just install that plugin in your Ionic app.
Then have a look at the README for running the server. That's that simple I think.
Thanks
