### ISSUE TITLE
Not Working !?

### ISSUE THREAD

**Issue by Dipayon3D** [becvert/cordova-plugin-websocket-server#41]
I am trying to use this plugin but I don't know why, it's not working . . . Do I need to turn the wifi on or is the plugin supposed to turn wifi on automatically ?

**Comment by becvert** [comment]
Wifi must be on. This plugin does not turn the wifi on.
Beware the origins and protocols options if you don't know what they are about.

**Comment by Dipayon3D** [comment]
Ok. . . is there any other requirements ?

**Comment by becvert** [comment]
Nope
