### ISSUE TITLE
[iOS] Xcode 9 / Swift 2.x error

### ISSUE THREAD

**Issue by vogloblinsky** [becvert/cordova-plugin-websocket-server#44]
With Xcode 9, i cannot open a Xcode project generated with Cordova CLI.

Xcode display a message about Swift 2.x

![image](https://user-images.githubusercontent.com/2841805/34294190-ace99b32-e707-11e7-993a-6bf93484744e.png)

Is it possible to migrate your iOS sources to Swift 3 ?

**Comment by becvert** [comment]
are you sure it's this plugin's fault?
it has been using Swift 3 for more than a year now.
I'll have a look but give me a couple of weeks.
Thanks

**Comment by vogloblinsky** [comment]
Ok sorry, i don't know what went wrong. It builds correctly now.

With this environment :
- macOS Sierra 10.12.6
- cordova 7.1.0
- Xcode 9.2

```
cordova create websocketservertest com.hello.world websocketservertest

cd websocketservertest

cordova platform add ios

cordova emulate ios // App runs fine on iPhone simulator

cordova plugin add cordova-plugin-websocket-server --save

cordova emulate ios // App runs fine on iPhone simulator again
```
