### ISSUE TITLE
[Android] Not working with Android 4.1.2

### ISSUE THREAD

**Issue by alsbtain** [becvert/cordova-plugin-websocket-server#45]
Thanks for the wonderful plugin! I tested it with Android 7.0, and it worked so well. However, when I tested it with Android 4.1.2, it did not work and no error message was given.

My code is available here: https://github.com/alsbtain/Communicator/blob/master/www/server.html

**Comment by becvert** [comment]
no alert in `onStart `or `onDidNotStart`?
no error message in log of Android Studio?

**Comment by alsbtain** [comment]
I get no alert messages. I am using Phonegap Build, not Android Studio. Debugging through Weinre gives no alerts either.

I have just tried the app with iOS 9.3.5 and it's not working. It may be a problem with my config.xml, but I am still unable to figure it out.

**Comment by becvert** [comment]
did you fix this?

**Comment by alsbtain** [comment]
The issue wasn't related to your plugin. I used some code in my project that wasn't supported in old devices. Your plugin works great!
