### ISSUE TITLE
How to send response to client using this websocket server

### ISSUE THREAD

**Issue by Gunasekaran15** [becvert/cordova-plugin-websocket-server#48]
How  to send a message  from websocket server to client side using this plugin

**Comment by Gunasekaran15** [comment]
please give some sample code

**Comment by becvert** [comment]
**README** [send](https://github.com/becvert/cordova-plugin-websocket-server#sendconn-msg)

**Comment by Gunasekaran15** [comment]
I have already applied that send method in my code,but it does't  give any response from server it sends ({issupported:true}) as data from server side.Please give some example to send message from server to client side.
