### ISSUE TITLE
How to broadcast message to all client using current web-socket server?

### ISSUE THREAD

**Issue by Danijel-Mekiho** [becvert/cordova-plugin-websocket-server#51]
I have setup one device as a web-socket server and I'm going to broadcast message to 5~10 client  devices.
But there isn't any function to implement above one in this plugin.
Please give me your opinion.

**Comment by becvert** [comment]
for now, keep the `connection` objects from the `onOpen` handler in an array and then loop the array and use `send` with the `connections`.
I may add a `broadcast` method in the future that would do exactly that.
