### ISSUE TITLE
var wsserver = cordova.plugins.wsserver; don't work

### ISSUE THREAD

**Issue by henokmengistu** [becvert/cordova-plugin-websocket-server#52]
hi, i was trying to use cordova-plugin-websocket-server and i am having difficulties with:
var wsserver = cordova.plugins.wsserver;
can u help me out, i used the the README, is there any other thing i need to import or install besides the plugin?

**Comment by becvert** [comment]
Hi. Can you please show us your code? client-side as well

**Comment by henokmengistu** [comment]
hi, if u have a sample code it will be appreciated

**Comment by henokmengistu** [comment]
sry

**Comment by KanshinC** [comment]
hey, I have the same problem. I work with capacitor and I installed the plugin. When I try to get wsserver, I got "wsserver does not exist on type 'CordovaPlugins'". It is listed in package.json and is also available in plugins folder.

Does anyone an idea for my problem?
