### ISSUE TITLE
[iOS] "Project Name" was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by rsax** [becvert/cordova-plugin-websocket-server#53]
Hi.

I have been receiving the message:
**[PROJECT NAME] was compiled with optimization - stepping may behave oddly; variables may not be available.**

This is happening on iOS when I send a message to the websocket server. When the cordova socket server receive the message the app crash. According to my investigation the problem is due to how the libPocketSocket.a was optimized during the build process. 

The same error was reported here using others libraries.

- https://stackoverflow.com/questions/32772573/project-name-was-compiled-with-optimization-stepping-may-behave-oddly-varia
- https://stackoverflow.com/questions/45078851/optimization-stepping-may-behave-oddly-ios-unity

I've been using this versions:
Cordova (Cordova CLI) : 8.0.0
Cordova Platforms: ios 4.5.5
iOS Deployment Target: 10.0

Here the error, pointing to PSWebSocketDriver._initialFrame

![image](https://user-images.githubusercontent.com/2637450/45611018-9fa7dc00-ba23-11e8-828b-b460e5f3d8c0.png)

I am triying to recompile PocketSocket.

Does anybody have an idea how to solve this issue?

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.

**Comment by mario-donnarumma** [comment]
Hi @rsax, I'm having the same issue. Did you solve it somehow?
