### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by Jerry-swat** [becvert/cordova-plugin-websocket-server#54]
Hello, I would like to ask wsserver. Start is sometimes normal at first. When I forcibly shut down the application process and re-enter the app, wsserver. Start does not respond, nor does it trigger failure. I would like to ask what causes this, which makes it impossible for me to monitor whether wsserver is turned on correctly.

**Comment by becvert** [comment]
Hello,
is this Android, iOS or both?
is there some debugging logs in Android Studio or XCode?
What's your wsserver start options?

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.
