### ISSUE TITLE
Cordova 9 support?

### ISSUE THREAD

**Issue by maxidirienzo** [becvert/cordova-plugin-websocket-server#58]
Trying to run an empty project with only this plugin throws this issue:

`Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Cordova version 9
Check this PR regarding Cordova change: https://github.com/apache/cordova-lib/pull/707

**Comment by becvert** [comment]
Hello,
We are aware of this.
This plugin is dependent on cordova-plugin-add-swift-support for iOS which does not support cordova-cli 9 yet. We're just waiting for it to be updated now. [akofman/cordova-plugin-add-swift-support#57](https://github.com/akofman/cordova-plugin-add-swift-support/pull/57)

**Comment by maxidirienzo** [comment]
Excellent, hope they release it soon.
Thanks.

**Comment by becvert** [comment]
Fixed!
