### ISSUE TITLE
How to change the ip address?

### ISSUE THREAD

**Issue by ayyazzafar** [becvert/cordova-plugin-websocket-server#6]
Hi, I reviewed your plugin. It looks awesome but unfortunately I could not get it working for me.

I have a websocket opened on a remote web server so I want to use a remote ip address instead of  0.0.0.0:2000

I could not find any option to change ip address. Can you please tell that how can we perform this?

Thanks

**Comment by becvert** [comment]
'0.0.0.0' means the server listens for incoming connections on all the network interfaces of your device.
You can't choose one interface in particular. This is the default with this plugin for now.
But most likely you only have one Wifi interface and one Bluetooth interface anyway.
If one of your network interface subnet is 192.168.0.x for instance then the server is accessible at 192.168.0.x:2000
Does that answer your question?

**Comment by ayyazzafar** [comment]
Thank you so much for quick response.

Actually I made a chat system by opening web socket on my remote web hosting. So my hosting is listening for a port. So I have to connect my mobile device with that remote socket from my web server.

**Comment by becvert** [comment]
If I follow you (I'm not sure I do), you just need a websocket client on your device to connect to your remote websocket server? No need for this cordova plugin. 
Don't you know the IP or your hosting service?

**Comment by OrdinarySF** [comment]
I made a [capacitor(ionic) plugin](https://github.com/OrdinarySF/capacitor-websocket-client) that can support websocket remote connection, welcome to try it.
