### ISSUE TITLE
onOpen event

### ISSUE THREAD

**Issue by piter921702** [becvert/cordova-plugin-websocket-server#7]
Hi, i have a question. I created TCP server on my mobile device. I try to connect to them from C# TcpClient, but onOpen and onMessage events is not hitting. What I make wrong?

This is my simple C# code:

```
            tcpClient.Connect("192.168.43.47", 2000);                

            string str = "test";
            Stream stm = tcpClient.GetStream();

            ASCIIEncoding asen = new ASCIIEncoding();
            byte[] ba = asen.GetBytes(str);                

            //sending message
            stm.Write(ba, 0, ba.Length);
```

**Comment by becvert** [comment]
Hi. You need to establish a **WebSocket** connection.
Use a C# **WebSocket** client (a TcpClient with WebSocket protocol) to allow that.
