### ISSUE TITLE
Example missing a coma

### ISSUE THREAD

**Issue by DMagnusPrime** [becvert/cordova-plugin-websocket-server#8]
I hate to admit it but I copied the code and you are missing a comma
In this line:
    'origins' : [ 'file://' ],

**Comment by becvert** [comment]
thank you!

**Comment by DMagnusPrime** [comment]
Well, a coma is no big deal as it is obviously not copy paste code. Though I really wanted to thank you, people who do Córdova plugins have a special place in heaven. 02:31, 22 de julio de 2016, becvert notifications@github.com:thank you! —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.     -- Sent from Yandex.Mail for mobile
