### ISSUE TITLE
Error Missing Command Error

### ISSUE THREAD

**Issue by DMagnusPrime** [becvert/cordova-plugin-websocket-server#9]
Would like to ask it as a question

When does this error occurs??
"Error "Missing Command Error""

Ran it with cordova run browser
Used you code modified like this. Thanks a lot for the plugins also.

var wsserver = cordova.plugins.wsserver;
             wsserver.start(3721, {
                // WebSocket Server
                'onStart' : function(addr, port) {
                    console.log('Listening on %s:%d', addr, port);
                },
                'onStop' : function(addr, port) {
                    console.log('Stopped listening on %s:%d', addr, port);
                },
                // WebSocket Connection
                'onOpen' : function(conn) {
                    /\* conn: {
                     'uuid' : '8e176b14-a1af-70a7-3e3d-8b341977a16e',
                     'remoteAddr' : '192.168.1.10',
                     'acceptedProtocol' : 'my-protocol-v1',
                     'httpFields' : {...},
                     'resource' : '/?param1=value1&param2=value2'
                     } */
                    console.log('A user connected from %s', conn);
                },
                'onMessage' : function(conn, msg) {
                    console.log(conn, msg);
                },
                'onClose' : function(conn, code, reason) {
                    console.log('A user disconnected from %s', conn.remoteAddr);
                },
                'origins' : [ 'file://' ], // optional. validates the 'Origin' HTTP Header.
                'protocols' : [ 'my-protocol-v1', 'my-protocol-v2' ] // optional. validates the 'Sec-WebSocket-Protocol' HTTP Header.
            });

```
```

**Comment by becvert** [comment]
Maybe because the browser platform isn't supported.
This plugin is Android & iOS only.

**Comment by DMagnusPrime** [comment]
You are right, an apology02:34, 22 de julio de 2016, becvert notifications@github.com:Maybe because the browser platform isn't supported. This plugin is Android & iOS only. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.     -- Sent from Yandex.Mail for mobile

**Comment by becvert** [comment]
no worries @DMagnusPrime
